@startuml

!define table(x) class x << (T,#FFAAAA) >>
hide methods

table(members) {
    <&key> id: int
    name: varchar
    surname: varchar
    display_name: varchar
    secret: varchar
    email_address: varchar
    reputation_points: int
    profile_pic: ?
    location: ?
}
table(accounts) {
    <&key> id: int
    member_id: int
    credits: int
    refused_count: int
}
table(tags) {
    <&key> id: int
    name: varchar
}

table(interests) {
    <&key> id: int
    member_id: int
    tag_id: int
}
table(strong_suits) {
    <&key> id: int
    member_id: int
    tag_id: int
}
table(service_tags) {
    <&key> id: int
    service_id: int
    tag_id: int
}
table(event_tags) {
    <&key> id: int
    event_id: int
    account_id: int
}
table(admins) {
    <&key> id: int
    name: varchar
    surname: varchar
    display_name: varchar
    secret: varchar
}
table(services) {
    <&key> id: int
    name: varchar
    description: varchar
    offerer_account_id: int
    time: date
    duration: int
    location: ?
    max_number_of_participants: int
    cancellationDeadline: int
    status: varchar
}
table(service_participants) {
    <&key> id: int
    service_id: int
    account_id: int
    request_status: varchar
}
table(events) {
    <&key> id: int
    name: varchar
    description: varchar
    offerer_account_id: int
    time: date
    duration: int
    location: ?
    status: varchar
}
table(event_participants) {
    <&key> id: int
    event_id: int
    account_id: int
}
table(service_feedbacks) {
    <&key> id: int
    service_id: int
    giver_account_id: int
    taker_account_id: int
    rating: int
    comment: varchar
}
table(event_feedback) {
    <&key> id: int
    event_id: int
    giver_account_id: int
    taker_account_id: int
    rating: int
    comment: varchar
}
members::id -- accounts::member_id : member_id
members::id -- interests::member_id : member_id
tags::id -- interests::tag_id : tag_id
members::id -- strong_suits::member_id : member_id
tags::id -- strong_suits::tag_id : tag_id
services::id -- service_tags::service_id
tags::id -- service_tags::tag_id : tag_id
event_id::service_id -- events::id : event_id
tags::id -- event_tags::tag_id : tag_id
services::offerer_account_id -- accounts::id : account_id
service_participants::service_id -- services::id : service_id
service_participants::account_id -- accounts::id : account_id
events::offerer_account_id -- accounts::id : account_id
event_participants::event_id -- events::id : event_id
event_participants::account_id -- accounts::id : account_id
service_feedbacks::service_id -- services::id : service_id
service_feedbacks::giver_account -- accounts::id : account_id
service_feedbacks::taker_account -- accounts::id : account_id
event_feedback::event_id -- events::id : event_id
event_feedback::giver_account_id -- accounts::id : account_id
event_feedback::taker_account_id -- accounts::id : account_id
@enduml