version: '3.7'
services:
  database:
    image: postgres
    container_name: akita-postgres
    environment:
      - POSTGRES_DB=akita
      - POSTGRES_USER=akita
      - POSTGRES_PASSWORD=4k1t4
      - TZ=Europe/Istanbul
      - PGTZ=Europe/Istanbul
    ports:
      - "5432:5432"

  akita:
    build: .
    container_name: akita-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/akita
      - SPRING_DATASOURCE_USERNAME=akita
      - SPRING_DATASOURCE_PASSWORD=4k1t4
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    links:
      - database
    depends_on:
      - database
