@startuml
enum FrequencyType {
    DAILY
    WEEKLY
    MONTHLY
}
class Tag {
    -id: Serial
    -name: String
    -color: String

    +addTag()
    +deleteTag()
}

abstract class Location {
    - latitude: double
    - longitude: double
    }

class MemberLocation {
    -memberId: Serial
}

MemberLocation --|> Location

class ServiceLocation {
    -serviceId: Serial
}
ServiceLocation --|> Location

class EventLocation {
    -eventId: Serial
}
EventLocation --|> Location
@enduml