@startuml
mainframe getting service

group getting service

actor receiver
actor offerer
participant Account
participant Service
database DB

receiver -> Service: apply(id)

activate Service
Service -> Account: verifyTimeCredits(id)
activate Account
alt successful case
    Account --> Service: validation successful
else failure
    Account --> receiver: validationError
deactivate Account
end
Service -> DB: register application

Service -> offerer: notifyOfferer(id, message)
deactivate Service
end
@enduml